name: flutter_messenger
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.3
  device_info_plus: ^8.1.0
  encrypt: ^5.0.1
  file_picker: ^5.2.5
  flutter_svg: ^2.0.4
  fast_cached_network_image: ^1.1.1
  http: ^0.13.5
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^2.3.0
  video_player: ^2.6.0
  video_player_macos: ^2.0.1
  video_player_win: ^2.2.2

  logger: ^1.2.2
  path_provider: ^2.0.13
  vchatcloud_flutter_sdk: ^1.0.7
  universal_html: ^2.2.1

  flutter_native_splash: ^2.0.5
  fluttertoast: ^8.2.1

  permission_handler: ^10.2.0

  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/common/
    - assets/profile/
    - assets/chat/
    - assets/img/emoticon/listImage/
    - assets/img/emoticon/emo01/
    - assets/img/emoticon/emo02/
    - assets/img/emoticon/emo03/
    - assets/img/emoticon/emo04/
    - assets/img/emoticon/emo05/
    - assets/img/emoticon/emo06/
    - assets/img/emoticon/emo07/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
